# Generated by Django 5.1.2 on 2025-03-11 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_video_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['id']},
        ),
    ]
